# Generated by Django 3.0 on 2020-02-17 13:44

import address.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField(validators=[address.models.check_pin_code])),
                ('active', models.CharField(default='Y', max_length=1, validators=[address.models.check_active])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Info_Address',
            },
            managers=[
                ('all_ent', django.db.models.manager.Manager()),
            ],
        ),
    ]
