# Generated by Django 3.0 on 2020-02-17 13:44

import address.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_no', models.BigIntegerField()),
                ('active', models.CharField(default='Y', max_length=1, validators=[address.models.check_active])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_ref', to='address.Address')),
            ],
            options={
                'db_table': 'Info_Hospital',
            },
            managers=[
                ('all_ent', django.db.models.manager.Manager()),
            ],
        ),
    ]
